// src/components/Alert.jsx
function Alert({ title, message, onCancel, onCancelAll, onConfirm }) {
  return (
    <>
      <div className="alert">
        <h3>{title}</h3>
        <p>{message}</p>
        <div className="btn-list">
          <button type="button" onClick={onCancel} className="alert-btn">
            Cancel
          </button>
          <button type="button" onClick={onCancelAll} className="alert-btn">
            Cancel All
          </button>
          <button type="button" onClick={onConfirm} className="alert-btn primary">
            Confirm
          </button>
        </div>
      </div>
      <div className="overlay" />
    </>
  );
}

export default Alert;

// src/components/Alert.svelte
<script>
  import { createEventDispatcher } from 'svelte';
  const dispatch = createEventDispatcher();

  export let title = '';
  export let message = '';

  const cancel = () => dispatch('cancel');
  const confirm = () => dispatch('confirm');
  const cancelAll = () => dispatch('cancel-all');
</script>

<div class="alert">
  <h3>{title}</h3>
  <p>{message}</p>
  <div class="btn-list">
    <button type="button" on:click={cancelAll} class="alert-btn"> Cancel All </button>
    <button type="button" on:click={cancel} class="alert-btn"> Cancel </button>
    <button type="button" on:click={confirm} class="alert-btn primary"> Confirm </button>
  </div>
</div>
<div class="overlay" />
