// src/components/Footer.jsx
import { gitRepo } from '../utils/constants';

function Footer() {
  return (
    <footer>
      <p>
        Copyright &copy; {new Date().getFullYear()} &nbsp;
        <a target="_blank" rel="noopener noreferrer" href="https://aromalanil.in/">
          Aromal Anil
        </a>
        &nbsp; |&nbsp;{' '}
        <a href={`${gitRepo}/blob/master/LICENSE`} target="_blank" rel="noopener noreferrer">
          MIT License
        </a>
      </p>
    </footer>
  );
}

export default Footer;

// src/components/Footer.svelte
<script>
  import { gitRepo } from '../utils/constants';
</script>

<footer>
  <p>
    Copyright &copy; {new Date().getFullYear()} &nbsp;
    <a target="_blank" rel="noopener noreferrer" href="https://aromalanil.in/"> Aromal Anil </a>
    &nbsp; |&nbsp;{' '}
    <a href={`${gitRepo}/blob/master/LICENSE`} target="_blank" rel="noopener noreferrer">
      MIT License
    </a>
  </p>
</footer>
