// src/lib/components/MessageList.svelte
<script lang="ts">
	import { createEventDispatcher } from 'svelte';
	import Alert from './Alert.svelte';

	const dispatch = createEventDispatcher();

	export let message = '';
	export let phoneNumbers: string[] = [];

	let activeIndex = 0;

	const dispatchStop = () => {
		dispatch('stop');
	};

	const incrementIndex = () => {
		if (activeIndex + 1 === phoneNumbers.length) dispatchStop();
		activeIndex = activeIndex + 1;
	};

	const sendMessage = () => {
		const phoneNumber = phoneNumbers[activeIndex];
		const newNumber = phoneNumber.toString().length === 10 ? `+91${phoneNumber}` : phoneNumber;

		const link = `https://api.whatsapp.com/send?phone=${newNumber}${
			message ? `&text=${encodeURIComponent(message)}` : ''
		}`;
		window.open(link, '_blank');
		incrementIndex();
	};

	$: alertMessage = `Send Message to ${phoneNumbers[activeIndex]}`;
</script>

<Alert
	title="Send Message"
	message={alertMessage}
	on:confirm={sendMessage}
	on:cancel={incrementIndex}
	on:cancel-all={dispatchStop}
/>

// src/components/MessageList.jsx
import { useState } from 'react';
import Alert from './Alert';

function MessageList({ stop, phoneNumbers, message }) {
  const [activeIndex, setActiveIndex] = useState(0);

  const incrementIndex = () => {
    if (activeIndex + 1 === phoneNumbers.length) stop();
    setActiveIndex((index) => index + 1);
  };

  const sendMessage = () => {
    const phoneNumber = phoneNumbers[activeIndex];
    const newNumber = phoneNumber.toString().length === 10 ? `+91${phoneNumber}` : phoneNumber;

    const link = `https://api.whatsapp.com/send?phone=${newNumber}${
      message && `&text=${encodeURIComponent(message)}`
    }`;
    window.open(link, '_blank');
    incrementIndex();
  };

  const alertMessage = `Send Message to ${phoneNumbers[activeIndex]}`;

  return (
    <Alert
      title="Send Message"
      message={alertMessage}
      onCancel={incrementIndex}
      onCancelAll={stop}
      onConfirm={sendMessage}
    />
  );
}

export default MessageList;
