// src/components/MessageBox.jsx
function MessageBox({ name, placeholder, value, onChange, small }) {
  const handleMessageChange = (e) => {
    onChange(e.target.value);
  };

  return (
    <label id="message-box-label" htmlFor={name}>
      {name}
      <textarea
        className={`message-box ${small ? 'small-box' : ''}`}
        value={value}
        name={name}
        id={name}
        placeholder={placeholder}
        onChange={handleMessageChange}
      />
    </label>
  );
}

export default MessageBox;

// src/components/MessageBox.svelte
<script lang="ts">
  export let name = '';
  export let value = '';
  export let isSmall = true;
  export let placeholder = '';
</script>

<label id="message-box-label" for={name}>
  {name}
  <textarea
    class={`message-box ${isSmall ? 'small-box' : ''}`}
    bind:value
    {name}
    id={name}
    {placeholder}
  />
</label>
