// src/lib/components/NavBar.svelte
<script>
	import Logo from './Logo.svelte';
	import ImageLink from './ImageLink.svelte';
	import DarkModeToggle from './DarkModeToggle.svelte';

	import logo from '../images/logo.svg';
	import githubLogo from '../images/github_logo.svg';
	import { gitRepo, appName } from '$lib/utils/constants';
</script>

<nav class="nav-bar">
	<Logo img={logo} title={appName} alt={appName} />
	<div class="nav-links">
		<DarkModeToggle />
		<ImageLink image={githubLogo} link={gitRepo} alt="Github Logo" />
	</div>
</nav>

// src/components/NavBar.jsx
import Logo from './Logo';
import logo from '../img/logo.svg';
import ImageLink from './ImageLink';
import DarkModeToggle from './DarkModeToggle';
import githubLogo from '../img/github_logo.svg';
import { appName, gitRepo } from '../utils/constants';

function NavBar() {
  return (
    <nav className="nav-bar">
      <Logo img={logo} title={appName} alt={appName} />
      <div className="nav-links">
        <DarkModeToggle />
        <ImageLink image={githubLogo} link={gitRepo} alt="Github Logo" />
      </div>
    </nav>
  );
}

export default NavBar;
