// src/App.svelte
<script lang="ts">
  import isDesktop from './store/isDesktop';
  import NavBar from './components/NavBar.svelte';
  import Footer from './components/Footer.svelte';
  import Description from './components/Description.svelte';
  import MessageForm from './components/MessageForm.svelte';
</script>

<NavBar />
<main class="main-section">
  {#if $isDesktop}
    <Description />
  {/if}
  <MessageForm />
</main>
<Footer />

// src/App.jsx
import NavBar from './components/NavBar';
import Footer from './components/Footer';
import useDesktop from './hooks/useDesktop';
import Description from './components/Description';
import MessageForm from './components/MessageForm';

function App() {
  const isDesktop = useDesktop();

  return (
    <>
      <NavBar />
      <main className="main-section">
        {isDesktop && <Description />}
        <MessageForm />
      </main>
      <Footer />
    </>
  );
}

export default App;
