// src/components/MessageForm.jsx
import { useState } from 'react';

import Tab from './Tab';
import PersonalMessage from './PersonalMessage';
import BroadcastMessage from './BroadcastMessage';

function MessageForm() {
  const [activeTab, setActiveTab] = useState('Personal');

  return (
    <div className="message-form">
      <Tab
        activeTab={activeTab}
        tabValues={['Personal', 'Broadcast']}
        setActiveTab={setActiveTab}
      />
      {activeTab === 'Personal' && <PersonalMessage />}
      {activeTab === 'Broadcast' && <BroadcastMessage />}
    </div>
  );
}

export default MessageForm;

// src/lib/components/MessageForm.svelte
<script lang="ts">
	import Tab from './Tab.svelte';
	import PersonalMessage from './PersonalMessage.svelte';
	import BroadCastMessage from './BroadCastMessage.svelte';

	let activeTab: 'Personal' | 'Broadcast' = 'Personal';

	$: isPersonal = activeTab === 'Personal';
	$: isBroadCast = activeTab === 'Broadcast';

	const setActiveTab = (newActiveTab: typeof activeTab) => {
		activeTab = newActiveTab;
	};
</script>

<div class="message-form">
	<Tab {activeTab} tabValues={['Personal', 'Broadcast']} {setActiveTab} />
	{#if isPersonal}
		<PersonalMessage />
	{/if}

	{#if isBroadCast}
		<BroadCastMessage />
	{/if}
</div>
